<script lang="ts">
  import { BookOpen, HelpCircle, X } from 'lucide-svelte';
  let {onclose}: {onclose:()=>void} = $props();
  const topics = ['Quick start', 'Writing & tables', 'Keyboard shortcuts', 'Voice guide', 'Sharing', 'Offline & PWA', 'Backups', 'Troubleshooting'] as const;
  let topic = $state<typeof topics[number]>('Quick start');
  function focusDialog(node: HTMLElement) {
    const previous = document.activeElement as HTMLElement | null;
    queueMicrotask(() => node.querySelector<HTMLButtonElement>('button')?.focus());
    const key = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { event.preventDefault(); event.stopPropagation(); onclose(); return; }
      if (event.key !== 'Tab') return;
      const controls = [...node.querySelectorAll<HTMLElement>('button,a[href]')].filter(control => control.getClientRects().length > 0);
      const first = controls[0], last = controls.at(-1);
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    node.addEventListener('keydown', key);
    return {destroy(){node.removeEventListener('keydown', key); previous?.isConnected && previous.focus();}};
  }
</script>

<div class="help-layer" role="presentation"><section class="help-panel" role="dialog" aria-modal="true" aria-labelledby="notes-help-title" tabindex="-1" use:focusDialog>
  <header><div><h2 id="notes-help-title"><HelpCircle size={22}/> Notes guide</h2><p>A little space to think. A few ways to make it yours.</p></div><button class="close" aria-label="Close Notes guide" onclick={onclose}><X size={20}/></button></header>
  <nav aria-label="Notes guide topics">{#each topics as item}<button aria-pressed={topic === item} onclick={() => topic = item}>{item}</button>{/each}</nav>
  <div class="content">
    {#if topic === 'Quick start'}
      <h3><BookOpen size={19}/> Your first note</h3>
      <ol><li><strong>Choose a notebook.</strong> Use the notebook menu, or create one with Add notebook.</li><li><strong>Capture an idea.</strong> Choose New note for a title, or Quick capture to start writing immediately.</li><li><strong>Choose how to write.</strong> Edit Markdown shows the source; Rich text writing gives you formatted editing. Preview is for reading, and Split shows source alongside its output.</li><li><strong>Check the save status.</strong> “All changes saved” confirms the note is saved. If saving fails or a conflict appears, keep the draft and use the offered recovery options.</li><li><strong>Make it easy to find.</strong> Pin important notes, add tags, or give a note a color from its list actions.</li></ol>
      <p class="tip">Hover over an icon to see its label. On phones, use the larger controls and the More menu for tools that do not fit.</p>
      <h3>Notes and tasks together</h3><p>Use a checklist inside a note, then open ToDo to see tasks across notebooks. Daily notes and templates give recurring ideas, plans and shopping lists a starting point.</p>
    {:else if topic === 'Writing & tables'}
      <h3>Write comfortably</h3><p>The toolbar groups text formatting, lists, inserts and structured content. Add links, images, attachments, code, quotations, tables or formulas without memorizing every Markdown shortcut. Use Undo and Redo to revisit edits.</p>
      <p>Press Enter on a list item to continue the list. Press Enter on an empty item to leave it. A wide table scrolls sideways inside the note so the rest of your text stays readable.</p>
      <h3>What travels with Markdown?</h3><p>Headings, emphasis, lists, links and code are portable. Many Markdown readers also support tables and checklists. Formula rendering and embedded media depend on the destination app.</p>
      <p>Markdown tables store their text and alignment. They have no standard syntax for column widths, row heights, text colors or cell backgrounds. HTML styling is interpreted differently by different readers.</p>
      <p class="tip">Note colors in the list organize your notes; they do not change text color. Draggable table sizing and text/cell colors are planned additions and are not enabled in this version. Their export behavior will be explained here when available.</p>
    {:else if topic === 'Keyboard shortcuts'}
      <h3>Keep your hands on the keyboard</h3>
      <p>Use Ctrl on Windows/Linux or ⌘ on Mac. Formatting shortcuts work only while the Notes editor is focused. They do not run in search fields, dialogs, or other panels.</p>
      <ul><li><strong>Ctrl/⌘ + B / I:</strong> bold / italic</li><li><strong>Ctrl/⌘ + Shift + X:</strong> strikethrough</li><li><strong>Ctrl/⌘ + K:</strong> insert a link</li><li><strong>Ctrl/⌘ + E:</strong> inline code</li><li><strong>Ctrl/⌘ + Shift + 7 / 8 / 9:</strong> numbered list / bullet list / quotation</li><li><strong>Ctrl/⌘ + Alt + 1 / 2 / 3:</strong> heading level 1 / 2 / 3 (Option on Mac)</li><li><strong>Ctrl/⌘ + Z:</strong> undo</li><li><strong>Ctrl/⌘ + Shift + Z or Ctrl/⌘ + Y:</strong> redo</li><li><strong>Ctrl/⌘ + F:</strong> find in the current editor</li><li><strong>Ctrl/⌘ + S:</strong> save the current note</li><li><strong>Ctrl/⌘ + Shift + N:</strong> quick capture within the focused Notes panel</li></ul>
      <p class="tip">Select text before formatting, or insert a marker at the cursor. Enter continues a list; Enter on an empty item exits it. Your browser or operating system may reserve some combinations.</p>
    {:else if topic === 'Voice guide'}
      <h3>Three different audio tools</h3><ul><li><strong>Read aloud:</strong> the speaker reads the note or selected text. Pause, resume or stop whenever you like. Follow reading highlights the paragraph in Preview and scrolls it into view; turn it off to browse elsewhere.</li><li><strong>Dictation:</strong> the speaking-person icon turns speech into text while editing. Review the transcript before inserting it.</li><li><strong>Voice note:</strong> the microphone records an audio attachment rather than turning speech into writing.</li></ul>
      <h3>Download only what you need</h3><p>The first use opens setup if a required model is missing. Audio settings let you download, preview, select or remove individual voices. On phones, Phone voices uses the local voices exposed by your browser. Downloaded voices is an optional alternative. Desktop starts with downloaded reading voices. Models and voices belong to this browser or device, not to your notebook.</p>
      <p>Downloaded reading uses Pocket TTS behind the scenes. Phone voices are admitted only when the browser identifies them as local; not every Siri or Google voice is available to a browser. Reading stays on your device; normal note saving and syncing still use Tend.</p>
      <p class="tip">Create my voice lets signed-in users record a short sample or upload a PCM WAV they have permission to use. The recording stays in memory; only the derived voice is saved in this browser for your account. It is not included in note exports or shared links. New voice creation currently supports English. Other languages and small catalog previews are future additions.</p>
    {:else if topic === 'Sharing'}
      <h3>Choose who can do what</h3><ol><li>Open a saved note and choose Share note.</li><li>Choose View only or Can edit, then an expiry. A passcode is optional; if you use one, send it separately from the link.</li><li>Choose Create link, then copy it, draft an email, or let the recipient scan the QR code.</li></ol><p>Anyone who receives the link can forward it. A guest does not need a Tend account, but must supply the passcode when one is set. Allow attachments only when you want editors to add media.</p>
      <h3>Work together in the shared editor</h3><p>While sharing is active, use the shared editor for collaboration. Private editing is paused to keep both paths from overwriting each other. Watch the connection and save status; a connection problem does not mean the last edit reached the server.</p><p>Revoke a link to end that link's access. Stop sharing when you want to resume private editing. Expiry and revocation do not erase copies a recipient already saved.</p>
      <h3>If collaboration needs recovery</h3><p>Use the sharing recovery controls to pause editing and inspect the preserved copies. Download the copies you need before choosing how to continue. Do not discard a version simply because it is not the currently displayed one.</p><p class="tip">Offline personal notes and live guest collaboration are different workflows. Do not assume a guest editing session is safely available offline; reconnect and check its status.</p>
    {:else if topic === 'Offline & PWA'}
      <h3>Install just Notes</h3><p>Open the standalone Notes app from Tend and sign in with your Tend credentials. Use Install Notes in its header. If the browser does not offer an install prompt, use its install or Add to Home Screen option; on iPhone, open the page in Safari and use Share → Add to Home Screen.</p><p>Installing the PWA adds a convenient app entry. It does not automatically download all notebooks, attachments or voice models.</p>
      <h3>Prepare before disconnecting</h3><ol><li>On a trusted device, open Notes settings and choose Set up offline editing.</li><li>Confirm Keep opened notes on this device and wait for preparation to finish.</li><li>Open the notes you will need while connected. Unopened notes and attachments still require a connection.</li><li>After editing offline, reconnect and check pending changes. Keep Notes open until syncing finishes.</li></ol><p>If the same note changed elsewhere, compare the versions and use the conflict-resolution controls. Notes preserves local changes so you can decide what to keep.</p><p class="tip">Offline notes are stored in this browser profile. Someone with access to that profile may read them. Avoid shared devices, and sync or export pending work before signing out, clearing browser data, or removing the app.</p>
    {:else if topic === 'Troubleshooting'}
      <h3>A voice or model will not download</h3><p>Check your connection and available device storage, then retry from Audio settings. Downloads are separate from your notes. Cancelled or failed downloads should leave already verified assets intact; removing all browser data is not a useful first troubleshooting step.</p>
      <h3>Read aloud pauses between paragraphs</h3><p>Reading prepares upcoming audio while the current section plays, but a slower device can still need more time. Read a smaller selection, close demanding tabs, or use Phone voices on mobile. A Preparing speech message means more audio is being generated; Stop cancels it. Repeating unchanged text can reuse audio already prepared in the current session.</p>
      <h3>Dictation cannot hear me</h3><p>Check the browser's microphone permission for Tend and your device's input selection. Close another recording or dictation session, then retry. Dictation is available while editing; the microphone voice-note tool records an attachment instead.</p>
      <h3>I cannot edit or saving is pending</h3><p>Check whether you are in Preview, using a view-only share, offline, or in an active sharing session. Switch to a writing mode only when you have edit permission. Keep a pending draft open, reconnect, and inspect any conflict or recovery message before closing it.</p>
      <h3>An update or sign-in interrupted me</h3><p>Preserve or export unsynced text first. Reconnect and sign in when requested, then check sync status. If an extension update failed safely, follow the displayed error and verify that both the panel and Notes are current before retrying.</p><p class="tip">When asking for help, include the Notes and Tend versions, browser/device, the action you took, and the exact error. Leave out note contents, passwords, share links and passcodes.</p>
    {:else}
      <h3>Offline is a device choice</h3><p>Use Notes settings to prepare this device for offline access. Confirm that preparation finishes before disconnecting. Watch pending changes and reconnect to sync; a conflict needs your attention so both versions can be preserved.</p>
      <h3>Export and back up</h3><p>Use Export Markdown for one note, or Export &amp; backups for a collection and its backup options. Keep a separate backup destination when possible. Exported Markdown remains yours to use in other apps.</p>
      <p>Attachments, application-specific features and styling may need extra files or support in the other reader. Check the export options and open a sample before relying on a migration.</p>
      <h3>Recovery and sharing</h3><p>Trash and recovery copies help you revisit changes where available. They are not a replacement for a separate backup. Share a note with the access level you intend, and revoke its link when you no longer need it.</p>
      <p class="tip">Clearing browser data can remove offline drafts and downloaded speech assets. Sync pending work or export it before clearing this device.</p>
    {/if}
  </div>
</section></div>

<style>
  .help-layer{position:absolute;inset:0;z-index:60;padding:16px;display:grid;place-items:center;background:color-mix(in srgb,var(--paper) 70%,transparent);backdrop-filter:blur(4px)}.help-panel{box-sizing:border-box;display:flex;flex-direction:column;width:min(680px,100%);max-height:100%;border:1px solid var(--line);border-radius:16px;background:var(--paper);color:var(--ink);box-shadow:0 20px 65px #0005;overflow:hidden}header{display:flex;align-items:flex-start;gap:12px;padding:20px 22px 12px;flex-shrink:0}header>div{flex:1;min-width:0}h2{display:flex;align-items:center;gap:9px;margin:0;font-size:20px}header p{font-size:12px;color:var(--soft);margin:6px 0 0}button{color:var(--ink);font:inherit;cursor:pointer}button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.close{display:grid;place-items:center;width:44px;height:44px;flex-shrink:0;border:1px solid var(--line);border-radius:10px;background:var(--wash)}nav{display:flex;gap:6px;flex-wrap:nowrap;overflow-x:auto;padding:0 22px 15px;border-bottom:1px solid var(--line);flex-shrink:0}nav button{flex-shrink:0;white-space:nowrap;min-height:40px;padding:8px 12px;font-size:12px;border:1px solid var(--line);border-radius:9px;background:var(--wash)}nav button[aria-pressed=true]{color:var(--accent-ink);background:var(--accent);border-color:var(--accent)}.content{padding:20px 24px;overflow:auto;overscroll-behavior:contain;font-size:13px;line-height:1.75}.content h3{display:flex;align-items:center;gap:8px;font-size:15px;margin:20px 0 7px}.content h3:first-child{margin-top:0}.content p{margin:9px 0}.content ul,.content ol{padding-left:22px;margin:10px 0}.content li{padding-left:3px;margin:10px 0}.tip{padding:12px 14px;border-left:3px solid var(--accent);border-radius:4px;background:var(--wash);color:var(--soft)}@container(max-width:520px){.help-layer{padding:8px}header{padding:15px 15px 10px}nav{padding:0 15px 12px;gap:5px}nav button{min-height:44px;flex:0 0 auto;font-size:12px}.content{padding:15px 18px;font-size:14px}h2{font-size:18px}}
</style>
