<script lang="ts">
  import { onMount } from 'svelte';
  import { Copy, ExternalLink, Link, LoaderCircle, QrCode, Send, ShieldCheck, X } from 'lucide-svelte';
  import type { Documents } from './host';
  type Sharing = NonNullable<Documents['sharing']>;
  let {sharing,noteId,prepare,oncreated,onstopped,onclose}: {sharing:Sharing;noteId:string;prepare:()=>Promise<boolean>;oncreated:()=>void;onstopped:()=>void|Promise<void>;onclose:()=>void}=$props();
  let links=$state<Array<{id:string;permission:'view'|'edit';expiresAt:number;allowAttachments:boolean;revoked?:boolean}>>([]);
  let permission=$state<'view'|'edit'>('view'), ttl=$state(86400), passcode=$state(''), allowAttachments=$state(false), busy=$state(false), error=$state(''), copied=$state(''), createdUrl=$state(''), qr=$state(''), sessionHref=$state(''), recovery=$state<{savedContent:string;currentContent:string;candidateContent:string|null;status:string}|null>(null);
  const date=(value:number)=>new Date(value*1000).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
  const canCreate=$derived(!busy && (!passcode || passcode.length>=6));
  async function refresh(){try{links=(await sharing.list(noteId)).items;}catch(cause){error=cause instanceof Error?cause.message:'Could not load sharing links.';}}
  async function create(){if(!canCreate)return;busy=true;error='';createdUrl='';qr='';try{if(!(await prepare()))return;const result=await sharing.create(noteId,{permission,passcode:passcode||null,ttlSeconds:ttl,allowAttachments:permission==='edit'&&allowAttachments});createdUrl=`${location.origin}/apps/shared-note/#invite=${encodeURIComponent(result.secret)}`;if(sharing.qr)qr=await sharing.qr(createdUrl);oncreated();await refresh();}catch(cause){error=cause instanceof Error?cause.message:'Could not create this sharing link.';}finally{busy=false;}}
  async function copy(){try{await navigator.clipboard.writeText(createdUrl);copied='Link copied.';}catch{copied='Could not copy the link. Select and copy it manually.';}}
  async function revoke(linkId:string){busy=true;error='';try{await sharing.revoke(noteId,linkId);await refresh();}catch(cause){error=cause instanceof Error?cause.message:'Could not revoke this link.';}finally{busy=false;}}
  async function openSession(){busy=true;error='';try{if(!(await prepare()))return;const result=await sharing.session(noteId);sessionHref=`${location.origin}/apps/shared-note/#session=${encodeURIComponent(result.session)}`;}catch(cause){error=cause instanceof Error?cause.message:'Could not open the shared editor.';}finally{busy=false;}}
  function download(content:string,name:string){const url=URL.createObjectURL(new Blob([content],{type:'text/markdown;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
  async function loadRecovery(){busy=true;error='';try{recovery=await sharing.recovery(noteId);}catch(cause){error=cause instanceof Error?cause.message:'Could not prepare the recovery copies.';}finally{busy=false;}}
  async function stop(){if(!confirm('Stop sharing? Existing guests will lose access, and you can download any recovery copies before reconciling private edits.'))return;busy=true;error='';try{await sharing.stop(noteId);await onstopped();sessionHref='';await refresh();}catch(cause){error=cause instanceof Error?cause.message:'Could not stop sharing.';}finally{busy=false;}}
  onMount(()=>{void refresh();});
</script>
<svelte:window onkeydown={event=>{if(event.key==='Escape'&&!busy){event.preventDefault();onclose();}}}/>
<div class="share-layer" role="presentation"><div class="share-dialog" role="dialog" aria-modal="true" aria-label="Share note" tabindex="-1">
  <header><div><h2><Link size={20}/> Share this note</h2><p>Anyone with this forwardable link can use it until it expires or you revoke it.</p></div><button class="close" aria-label="Close sharing" onclick={onclose} disabled={busy}><X size={19}/></button></header>
  <section><h3>Create a link</h3><label>Access<select bind:value={permission} disabled={busy}><option value="view">View only</option><option value="edit">Can edit</option></select></label><label>Expires<select bind:value={ttl} disabled={busy}><option value={3600}>1 hour</option><option value={86400}>1 day</option><option value={604800}>7 days</option><option value={2592000}>30 days</option></select></label><label>Passcode (optional)<input aria-label="Share passcode" type="password" minlength="6" bind:value={passcode} disabled={busy}/></label>{#if passcode}<small>Share the passcode separately from the link.</small>{/if}{#if permission==='edit'}<label class="check"><input type="checkbox" bind:checked={allowAttachments} disabled={busy}/> Let editors attach media</label>{/if}<button class="primary" disabled={!canCreate} onclick={()=>void create()}>{#if busy}<LoaderCircle size={15} class="spin"/> Creating…{:else}<Link size={15}/> Create link{/if}</button></section>
  {#if createdUrl}<section class="created"><h3><ShieldCheck size={17}/> Link created</h3><input aria-label="Sharing link" readonly value={createdUrl}/><div class="actions"><button onclick={()=>void copy()}><Copy size={15}/> Copy link</button><a href={`mailto:?subject=${encodeURIComponent('Shared Tend Note')}&body=${encodeURIComponent(createdUrl)}`}><Send size={15}/> Draft email</a></div>{#if copied}<p role="status">{copied}</p>{/if}{#if qr}<img class="qr" src={qr} alt="QR code for sharing link"/>{:else if sharing.qr}<p><QrCode size={15}/> Preparing QR code…</p>{/if}<p>Use shared editor while sharing is active. Stop sharing to resume private editing.</p></section>{/if}
  <section><h3>Shared editor</h3><p>Open the collaboration editor after your private draft has saved.</p><button onclick={()=>void openSession()} disabled={busy}><ExternalLink size={15}/> Prepare shared editor</button>{#if sessionHref}<a class="open" href={sessionHref}><ExternalLink size={15}/> Open shared editor</a>{/if}</section>
  <section><h3>Recovery copies</h3><p>Pause shared editing and preserve the last acknowledged copy, current saved note, and any pending changes. Guests cannot edit again until you stop sharing and create a new link.</p><button onclick={()=>void loadRecovery()} disabled={busy}>Pause sharing and prepare recovery copies</button>{#if recovery}<p>{recovery.status}</p><div class="actions"><button onclick={()=>download(recovery!.savedContent,'shared-note-saved.md')}>Download saved copy</button>{#if recovery.currentContent !== recovery.savedContent}<button onclick={()=>download(recovery!.currentContent,'shared-note-current.md')}>Download current copy</button>{/if}{#if recovery.candidateContent !== null}<button onclick={()=>download(recovery!.candidateContent!,'shared-note-candidate.md')}>Download candidate copy</button>{/if}</div>{/if}</section>
  <section><h3>Existing links</h3>{#if links.length}<ul>{#each links as link (link.id)}<li><span>{link.permission==='edit'?'Can edit':'View only'} · expires {date(link.expiresAt)}{#if link.allowAttachments} · attachments{/if}{#if link.revoked} · revoked{/if}</span>{#if !link.revoked}<button onclick={()=>void revoke(link.id)} disabled={busy}>Revoke</button>{/if}</li>{/each}</ul>{:else}<p>No active links.</p>{/if}<button class="danger" onclick={()=>void stop()} disabled={busy}>Stop sharing</button><small>Stopping invalidates collaboration access. Tend keeps the recovery candidate available for you to reconcile after private editing resumes.</small></section>
  {#if error}<p class="error" role="alert">{error}</p>{/if}
</div></div>
<style>
.share-layer{position:absolute;inset:0;z-index:30;padding:16px;display:grid;place-items:center;background:color-mix(in srgb,var(--paper) 68%,transparent);backdrop-filter:blur(3px)}.share-dialog{width:min(560px,100%);max-height:100%;overflow:auto;background:var(--paper);color:var(--ink);border:1px solid var(--line);border-radius:14px;padding:22px;box-shadow:0 20px 70px #0004}header{display:flex;gap:12px}h2,h3,p{margin:0}h2{display:flex;align-items:center;gap:8px;font-size:19px}header p,p,small{display:block;color:var(--soft);font-size:11px;line-height:1.6;margin-top:5px}.close{margin-left:auto;border:0;background:none;color:var(--ink);width:44px;height:44px}section{border-top:1px solid var(--line);padding-top:16px;margin-top:16px}h3{font-size:13px}label{display:block;font-size:11px;margin-top:10px}input,select{box-sizing:border-box;display:block;width:100%;margin-top:5px;padding:10px;background:var(--wash);color:var(--ink);border:1px solid var(--line);border-radius:7px}.check{display:flex;gap:8px;align-items:center}.check input{width:18px;margin:0}.primary,button,a{font:inherit}.primary,section>button,.actions button,.actions a,.open{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--line);border-radius:7px;padding:10px 12px;margin-top:12px;background:var(--wash);color:var(--ink);text-decoration:none;font-size:11px}.primary{background:var(--accent);color:var(--accent-ink);border:0}.actions{display:flex;gap:8px;flex-wrap:wrap}.qr{display:block;width:132px;height:132px;margin-top:12px;background:white;padding:5px}.created{background:color-mix(in srgb,var(--accent) 7%,var(--paper));padding:14px;border-radius:9px}ul{list-style:none;padding:0;margin:10px 0}li{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--line);font-size:11px}li button,.danger{color:var(--ink);background:none;border:0;text-decoration:underline}.danger{color:#d97872}.error{color:#d97872}@container(max-width:520px){.share-layer{padding:8px}.share-dialog{padding:17px}.actions>*{width:100%;justify-content:center}}
</style>
